# Generated by Django 2.0.7 on 2019-12-02 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date selected')),
                ('time', models.TimeField(verbose_name='time selected')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_subject', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150)),
                ('degree', models.CharField(max_length=150)),
                ('experience', models.IntegerField()),
                ('professional_statement_text', models.TextField()),
                ('education', models.TextField()),
                ('payment_statement', models.TextField()),
                ('start_duty_day', models.CharField(max_length=9)),
                ('end_duty_day', models.CharField(max_length=9)),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('presenting_complaint', models.TextField(blank=True, null=True)),
                ('presenting_complaint_detail', models.TextField(blank=True, null=True)),
                ('past_medical_history', models.TextField(blank=True, null=True)),
                ('past_surgical_history', models.TextField(blank=True, null=True)),
                ('past_drug_history', models.TextField(blank=True, null=True)),
                ('drug_allergy', models.TextField(blank=True, null=True)),
                ('vaccination_history', models.TextField(blank=True, null=True)),
                ('personal_history', models.TextField(blank=True, null=True)),
                ('economic_status', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150)),
                ('degree', models.CharField(max_length=150)),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150)),
                ('degree', models.CharField(max_length=150)),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='pages.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150)),
                ('experience', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=30)),
                ('date', models.DateField(verbose_name='date of report generation')),
                ('result_summary', models.CharField(max_length=200)),
                ('investigations', models.TextField()),
                ('test_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.Doctor')),
                ('lab_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.LabDoc')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=50)),
                ('service_summary', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=200)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialization', to='pages.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Person'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Person'),
        ),
        migrations.AddField(
            model_name='labdoc',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Person'),
        ),
        migrations.AddField(
            model_name='history',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_history', to='pages.Patient'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Person'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='pages.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='pages.Doctor'),
        ),
    ]
